Hw03 mongodb
vladislav-kulachko/nodejs-homework-rest-api pull request #2
Opened 2021-11-23 19:45 UTC by vladislav-kulachko

2021-11-24 19:54 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://vladcool:ldYVlIHz8NuEbRfC@cluster0.1j1mc.mongodb.net/db-contacts?retryWrites=true&w=majority
удалить этот файл из репозитория и добавить в gitignore

2021-11-24 19:54 UTC, KirillKulakow commented on bin/server.js
> +;(async () => {
зачем ; ?

2021-11-24 19:55 UTC, KirillKulakow commented on bin/server.js
> +    await mongoose.connect(DB_HOST)
добавь выдачу консоль лог при успешном подключении к базе

2021-11-24 19:56 UTC, KirillKulakow commented on routes/api/contacts.js
> +    await Contact.findById(contactId, (err, data) => {
стоп
или ты используешь async/await или callbacks 
вместе не дано

2021-11-24 19:57 UTC, KirillKulakow commented on routes/api/contacts.js
> +    await Contact.findByIdAndDelete(contactId, (err, data) => {
тоже самое!

2021-11-24 19:57 UTC, KirillKulakow commented on routes/api/contacts.js
> +        (err, data) => {
тоже самое

2021-11-24 19:58 UTC, KirillKulakow commented on routes/api/contacts.js
> +        if (err || data === null) {
тоже самое

2021-11-24 19:59 UTC, KirillKulakow requested changes
need fix

2021-11-25 10:01 UTC, vladislav-kulachko commented on bin/server.js
> +;(async () => {
// getting-started.js
const mongoose = require('mongoose');
main().catch(err => console.log(err));
async function main() {
  await mongoose.connect('mongodb://localhost:27017/test');
}
линтер ругается на не вызванную функцию

2021-11-25 10:03 UTC, vladislav-kulachko commented on .env
> +DB_HOST=mongodb+srv://vladcool:ldYVlIHz8NuEbRfC@cluster0.1j1mc.mongodb.net/db-contacts?retryWrites=true&w=majority
сделано

2021-11-25 10:03 UTC, vladislav-kulachko commented on bin/server.js
> +    await mongoose.connect(DB_HOST)
сделано

2021-11-25 13:16 UTC, vladislav-kulachko commented on routes/api/contacts.js
> +    await Contact.findById(contactId, (err, data) => {
сделано

2021-11-25 19:56 UTC, KirillKulakow commented on routes/api/contacts.js
>        throw new NotFound(`Contact with id ${contactId} not found`)
здесь лучше отдать badRequest, а вот если контакт не найден (вернется undefined) вернуть notFound

2021-11-25 19:57 UTC, KirillKulakow commented on routes/api/contacts.js
>        throw new NotFound(`Delete fail. Contact with id ${contactId} not found`)
так же

2021-11-25 19:57 UTC, KirillKulakow commented on routes/api/contacts.js
> +      if (!mongoose.Types.ObjectId.isValid(contactId)) {
то же поправить

2021-11-25 19:57 UTC, KirillKulakow requested changes
Need some fix

2021-11-26 20:03 UTC, KirillKulakow approved these changes

2021-11-27 02:26 UTC, merged