Hw04 auth
vladislav-kulachko/nodejs-homework-rest-api pull request #3
Opened 2021-11-27 15:54 UTC by vladislav-kulachko

2021-11-27 18:34 UTC, KirillKulakow commented on controllers/auth/register.js
> +  newUser.save()
save() is async function

2021-11-27 18:37 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const {page = null, limit = null} = req.query
лучше сделать проверку входящие параметров на число, если не число вернуть badRequest

2021-11-27 18:39 UTC, KirillKulakow commented on controllers/contacts/getById.js
> +  const data = await Contact.findById(contactId)
лучше добавить поиск не только по ид но и под ид собственника

2021-11-27 18:40 UTC, KirillKulakow commented on controllers/contacts/patchFavorite.js
> +  const data = await Contact.findById(contactId)
переделать проверку с поиском по ид собственника

2021-11-27 18:42 UTC, KirillKulakow commented on controllers/contacts/putById.js
> +  const data = await Contact.findByIdAndUpdate(contactId, req.body, {
переделать поиск

2021-11-27 18:42 UTC, KirillKulakow commented on controllers/contacts/removeById.js
> +  const data = await Contact.findByIdAndDelete(contactId)
переделать проверку

2021-11-27 18:42 UTC, KirillKulakow commented on routes/api/auth.js
> +router.post(
отсутствует шаг 5

2021-11-27 18:43 UTC, KirillKulakow requested changes
Need fix

2021-11-28 03:36 UTC, vladislav-kulachko commented on controllers/contacts/getAll.js
> +  const {page = null, limit = null} = req.query
Это для того чтобы небыло ошибки если их нет вообще, иначе ругается на отрицательные значения)

2021-11-28 03:41 UTC, vladislav-kulachko commented on controllers/auth/register.js
> +  newUser.save()
Богдан писал без. Но по логике да, исправил.

2021-11-28 04:23 UTC, vladislav-kulachko commented on routes/api/auth.js
> +router.post(
Упс, пропустил. Готово.

2021-11-29 22:29 UTC, KirillKulakow commented on controllers/auth/getUser.js
> +  const token = req.headers.authorization.split(" ")[1]
зачем тебе это если тебе приходит ид пользователя в req.user

2021-11-29 22:30 UTC, KirillKulakow commented on controllers/auth/patchStatus.js
> +  const token = req.headers.authorization.split(" ")[1]
зачем? если есть req.user

2021-11-29 22:30 UTC, KirillKulakow requested changes
Need fix

2021-11-30 08:03 UTC, vladislav-kulachko commented on controllers/auth/patchStatus.js
> +  const token = req.headers.authorization.split(" ")[1]
Ну а тут я просто следовал логике выше)

2021-11-30 08:03 UTC, vladislav-kulachko commented on controllers/auth/getUser.js
> +  const token = req.headers.authorization.split(" ")[1]
Ну так в задании же сказано получить пользователя по токену. Или я что-то не так понял и можно по id.

2021-11-30 21:05 UTC, KirillKulakow approved these changes

2021-12-01 08:56 UTC, merged